const CATEGORIES=[{id:"sunday1",label:"주일 1부"},{id:"sunday2",label:"주일 2부"},{id:"wednesday",label:"수요 예배"},{id:"core",label:"핵심 메시지"},{id:"romans16",label:"로마서 16장"},{id:"theology237",label:"237 전도 신학원"},{id:"camp",label:"합숙 메시지"},{id:"special",label:"특별 메시지"}];
const state={sermons:[],active:"sunday1",query:"",page:0,direction:"next",selected:null,detailFilters:[],fontSize:16};
const transcriptSearchState={hits:[],index:-1};
const $=id=>document.getElementById(id); const escapeHtml=s=>String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
function phrase(q){return q.trim().replace(/\s+/g," ").toLowerCase()}
function aliases(d){const[y,m,day]=d.split("-").map(Number),mm=String(m).padStart(2,"0"),dd=String(day).padStart(2,"0");return[d,`${y}-${m}-${day}`,`${y}.${m}.${day}`,`${y}. ${m}. ${day}.`,`${y}/${m}/${day}`,`${y}년 ${m}월 ${day}일`,`${y}${mm}${dd}`,`${m}/${day}`,`${mm}/${dd}`,`${m}-${day}`,`${m}.${day}`,`${m}월 ${day}일`,`${m}월${day}일`].join(" ").toLowerCase()}
function semesterLabel(value){return value==="spring"?"봄학기":value==="fall"?"가을학기":""}
function detailLabel(x){if(x.categoryId==="special")return x.seriesLabel||"";if(x.categoryId==="romans16"||x.categoryId==="theology237")return[x.programYear?`${x.programYear}년`:"",semesterLabel(x.semester)].filter(Boolean).join(" ");if(x.categoryId==="camp")return x.campRound?`${x.campRound}차`:"";return""}
function tone(value){let hash=0;for(const char of value)hash=(hash*31+char.charCodeAt(0))>>>0;return hash%6+1}
function matches(x,q){const needle=phrase(q);return !needle||[x.title,x.passage,x.content,detailLabel(x),aliases(x.date)].join(" ").replace(/\s+/g," ").toLowerCase().includes(needle)}
function highlight(text,q,force=false){const needle=phrase(q),html=escapeHtml(text);if(!needle||!String(text).replace(/\s+/g," ").toLowerCase().includes(needle))return force&&needle?`<mark class="search-highlight">${html}</mark>`:html;const re=new RegExp(`(${needle.replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace(/ /g,"\\s+")})`,`gi`);return html.replace(re,'<mark class="search-highlight">$1</mark>')}
function excerptHtml(content,q){const text=String(content??"").replace(/\s+/g," ").trim(),lower=text.toLowerCase(),needle=phrase(q),matchIndex=needle?lower.indexOf(needle):-1,center=matchIndex>=0?matchIndex:0,start=Math.max(0,center-(matchIndex>=0?48:0)),end=Math.min(text.length,Math.max(start+135,center+87)),snippet=`${start?"…":""}${text.slice(start,end)}${end<text.length?"…":""}`;return highlight(snippet,q)}
function formatDate(d){const[y,m,day]=d.split("-").map(Number);return`${y}. ${m}. ${day}.`}
function pages(){const list=state.sermons.filter(x=>x.categoryId===state.active&&(!state.detailFilters.length||state.detailFilters.includes(detailLabel(x)))&&matches(x,state.query));const grouped={};list.forEach(x=>(grouped[x.date.slice(0,7)]??=[]).push(x));return Object.entries(grouped).sort(([a],[b])=>b.localeCompare(a)).map(([month,sermons])=>({month,sermons:sermons.sort((a,b)=>b.date.localeCompare(a.date))}))}
function renderTabs(){$("tabs").innerHTML=CATEGORIES.map(c=>`<button role="tab" aria-selected="${state.active===c.id}" class="tab ${state.active===c.id?'active':''}" data-tab="${c.id}">${c.label}</button>`).join("");document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{state.active=b.dataset.tab;state.detailFilters=[];state.page=0;state.direction="next";render()});renderDetailFilters()}
function renderDetailFilters(){const options=[...new Set(state.sermons.filter(x=>x.categoryId===state.active).map(detailLabel).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ko",{numeric:true}));const box=$("detail-filters");if(!options.length){box.classList.add("is-hidden");return}box.classList.remove("is-hidden");$("detail-filter-title").textContent=state.active==="special"?"특별 메시지 항목":state.active==="camp"?"합숙 차수":"연도·학기";$("detail-filter-options").innerHTML=options.map(value=>`<label class="detail-filter detail-tone-${tone(value)}"><input type="checkbox" value="${escapeHtml(value)}" ${state.detailFilters.includes(value)?"checked":""}><span>${escapeHtml(value)}</span></label>`).join("");$("detail-filter-options").querySelectorAll("input").forEach(input=>input.onchange=()=>{state.detailFilters=input.checked?[...state.detailFilters,input.value]:state.detailFilters.filter(value=>value!==input.value);state.page=0;render()})}
function render(){renderTabs();const ps=pages(),current=ps[Math.min(state.page,Math.max(ps.length-1,0))];if(current){const[y,m]=current.month.split("-");$("month-pagination").classList.remove("is-hidden");$("month-pagination").innerHTML=`<div class="month-heading"><span>Monthly archive</span><strong>${y}년 ${Number(m)}월</strong><small>${state.page+1} / ${ps.length} 페이지</small></div><div class="month-buttons"><button id="older" ${state.page>=ps.length-1?'disabled':''}>← 이전 페이지</button><button id="newer" ${state.page===0?'disabled':''}>다음 페이지 →</button></div>`;$("older").onclick=()=>{state.page++;state.direction="previous";render()};$("newer").onclick=()=>{state.page--;state.direction="next";render()}}else{$("month-pagination").classList.add("is-hidden")}
  const cards=$("cards");cards.className=`cards month-page month-page-${state.direction}`;cards.innerHTML=current?current.sermons.map(x=>`<article class="card card-${x.categoryId}"><div class="card-meta"><span class="badge">${x.category}</span><time class="card-date" datetime="${x.date}">${highlight(formatDate(x.date),state.query,Boolean(phrase(state.query))&&aliases(x.date).includes(phrase(state.query)))}</time></div>${detailLabel(x)?`<span class="detail-badge detail-tone-${tone(detailLabel(x))}">${escapeHtml(detailLabel(x))}</span>`:""}<button class="card-title" data-open="${x.id}">${highlight(x.title,state.query)}</button>${x.passage?`<p class="passage">${highlight(x.passage,state.query)}</p>`:""}<p class="card-excerpt">${excerptHtml(x.content,state.query)}</p><div class="card-bottom"><button class="card-read" data-open="${x.id}">말씀 전체 읽기 <span class="read-arrow">→</span></button></div></article>`).join(""):`<div class="empty"><strong>첫 말씀을 기다리고 있습니다</strong>${state.query||state.detailFilters.length?'검색·분류 조건에 맞는 녹취록이 없습니다.':`${CATEGORIES.find(c=>c.id===state.active).label} 녹취록이 등록되면 이곳에 최신순으로 나타납니다.`}</div>`;document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openModal(b.dataset.open))}
function clean(html){const doc=new DOMParser().parseFromString(html,"text/html"),allowed=new Set(["P","BR","B","STRONG","U","SPAN"]);[...doc.body.querySelectorAll("*")].reverse().forEach(el=>{if(!allowed.has(el.tagName)){el.replaceWith(...el.childNodes);return}const bg=el.tagName==="SPAN"?el.style.backgroundColor:"";[...el.attributes].forEach(a=>el.removeAttribute(a.name));if(el.tagName==="SPAN"&&bg)el.style.backgroundColor="rgb(255, 241, 138)"});return doc.body.innerHTML}
function baseHtml(content){return content.split(/\n{2,}/).filter(Boolean).map(p=>`<p>${escapeHtml(p)}</p>`).join("")}
function annotationMatchesContent(html,content){const doc=new DOMParser().parseFromString(html,"text/html"),saved=[...doc.body.querySelectorAll("p")].map(p=>p.textContent||"").join("\n\n")||doc.body.textContent||"",normalize=value=>String(value||"").replace(/\r\n?/g,"\n").replace(/\u00a0/g," ").split("\n").map(line=>line.replace(/[\t ]+/g," ").trimEnd()).join("\n").trim();return normalize(saved)===normalize(content)}
function removeTranscriptSearchMarks(){document.querySelectorAll("#transcript mark.transcript-search-hit").forEach(mark=>mark.replaceWith(...mark.childNodes));$("transcript").normalize()}
function showTranscriptHit(index){const hits=transcriptSearchState.hits;if(!hits.length){transcriptSearchState.index=-1;$("transcript-search-count").textContent="0개";return}transcriptSearchState.index=(index+hits.length)%hits.length;hits.forEach((hit,i)=>hit.classList.toggle("is-current",i===transcriptSearchState.index));$("transcript-search-count").textContent=`${transcriptSearchState.index+1}/${hits.length}`;hits[transcriptSearchState.index].scrollIntoView({block:"center",behavior:"smooth"})}
function searchTranscript(query,{jump=true}={}){removeTranscriptSearchMarks();transcriptSearchState.hits=[];transcriptSearchState.index=-1;const needle=query.trim();if(!needle){$("transcript-search-count").textContent="";return}const lowerNeedle=needle.toLowerCase(),walker=document.createTreeWalker($("transcript"),NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>{const text=node.nodeValue,lower=text.toLowerCase();if(!lower.includes(lowerNeedle))return;const fragment=document.createDocumentFragment();let cursor=0,index=lower.indexOf(lowerNeedle);while(index>=0){fragment.append(text.slice(cursor,index));const mark=document.createElement("mark");mark.className="transcript-search-hit";mark.textContent=text.slice(index,index+needle.length);fragment.append(mark);transcriptSearchState.hits.push(mark);cursor=index+needle.length;index=lower.indexOf(lowerNeedle,cursor)}fragment.append(text.slice(cursor));node.replaceWith(fragment)});if(jump)showTranscriptHit(0);else $("transcript-search-count").textContent=transcriptSearchState.hits.length?`1/${transcriptSearchState.hits.length}`:"0개"}
function updateFontSize(){$("transcript").style.fontSize=`${state.fontSize}px`;$("font-size-value").textContent=`${state.fontSize}px`;$("font-smaller").disabled=state.fontSize<=16;$("font-larger").disabled=state.fontSize>=24}
function openModal(id,{pushHistory=true}={}){const x=state.sermons.find(s=>String(s.id)===String(id));if(!x)return;state.selected=x;state.fontSize=16;updateFontSize();$("share-notice").textContent="";$("modal-meta").innerHTML=`${x.category}${detailLabel(x)?` · ${escapeHtml(detailLabel(x))}`:""} · ${highlight(formatDate(x.date),state.query)}`;$("sermon-title").innerHTML=highlight(x.title,state.query);$("modal-passage").innerHTML=highlight(x.passage||"",state.query);$("modal-passage").hidden=!x.passage;$("print-link").href=`./print.html?id=${encodeURIComponent(x.id)}`;const annotationKey=`sermon-annotation-${x.id}`,saved=localStorage.getItem(annotationKey),useSaved=Boolean(saved&&annotationMatchesContent(saved,x.content));if(saved&&!useSaved){localStorage.removeItem(annotationKey);$("annotation-guide").firstChild.textContent="말씀이 수정되어 최신 본문을 불러왔습니다. 이전 본문에 남긴 효과는 초기화되었습니다. ";}$("transcript").innerHTML=useSaved?clean(saved):baseHtml(x.content);$("transcript-search").value=state.query.trim();$("modal-backdrop").classList.remove("is-hidden");document.body.style.overflow="hidden";searchTranscript($("transcript-search").value,{jump:Boolean($("transcript-search").value)});if(pushHistory&&String(history.state?.sermonId)!==String(x.id)){const url=new URL(location.href);url.hash=`sermon-${encodeURIComponent(x.id)}`;history.pushState({sermonId:String(x.id)},"",url)}}
function sermonIdFromHash(){const match=location.hash.match(/^#sermon-(.+)$/);return match?decodeURIComponent(match[1]):""}
async function shareSelected(){if(!state.selected)return;const x=state.selected,url=new URL(location.href);url.hash=`sermon-${encodeURIComponent(x.id)}`;const data={title:x.title,text:`${x.title} · ${formatDate(x.date)}`,url:url.href};if(navigator.share){try{await navigator.share(data);$("share-notice").textContent="공유 화면을 열었습니다.";return}catch(error){if(error?.name==="AbortError")return}}try{await navigator.clipboard.writeText(url.href);$("share-notice").textContent="말씀 링크를 복사했습니다. 카카오톡에 붙여넣어 전달할 수 있습니다."}catch{prompt("아래 말씀 링크를 복사해 주세요.",url.href);$("share-notice").textContent="말씀 링크를 준비했습니다."}}
function hideModal(){$("modal-backdrop").classList.add("is-hidden");document.body.style.overflow="";state.selected=null}
function closeModal(){if(state.selected&&String(history.state?.sermonId)===String(state.selected.id))history.back();else hideModal()}
function save(){if(state.selected)localStorage.setItem(`sermon-annotation-${state.selected.id}`,clean($("transcript").innerHTML))}
$("share-sermon").onclick=shareSelected;
$("font-smaller").onclick=()=>{state.fontSize=Math.max(16,state.fontSize-2);updateFontSize()};
$("font-larger").onclick=()=>{state.fontSize=Math.min(24,state.fontSize+2);updateFontSize()};
$("search").oninput=e=>{state.query=e.target.value;state.page=0;render()};$("transcript-search").oninput=e=>searchTranscript(e.target.value);$("transcript-search-prev").onclick=()=>showTranscriptHit(transcriptSearchState.index-1);$("transcript-search-next").onclick=()=>showTranscriptHit(transcriptSearchState.index+1);$("close-modal").onclick=closeModal;$("modal-backdrop").onmousedown=e=>{if(e.target===$("modal-backdrop"))closeModal()};document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});document.querySelectorAll("[data-command]").forEach(b=>b.onmousedown=e=>{e.preventDefault();const sel=getSelection();if(!sel||sel.isCollapsed||!$("transcript").contains(sel.anchorNode)||!$("transcript").contains(sel.focusNode)){$("annotation-guide").firstChild.textContent="먼저 녹취록 안에서 효과를 적용할 문장을 선택해 주세요.";return}document.execCommand(b.dataset.command,false,b.dataset.command==="hiliteColor"?"#fff18a":undefined);save()});$("clear-effects").onmousedown=e=>{e.preventDefault();if(state.selected&&confirm("이 말씀에 표시한 모든 효과를 지울까요?")){localStorage.removeItem(`sermon-annotation-${state.selected.id}`);$("transcript").innerHTML=baseHtml(state.selected.content);searchTranscript($("transcript-search").value,{jump:false})}};$("transcript").oninput=save;
window.addEventListener("popstate",()=>{const sermonId=history.state?.sermonId||sermonIdFromHash();if(sermonId)openModal(sermonId,{pushHistory:false});else hideModal()});
function normalizeSermons(data){return data.map(x=>({...x,seriesLabel:x.seriesLabel||"",programYear:x.programYear||null,semester:x.semester||"",campRound:x.campRound||null,categoryId:CATEGORIES.find(c=>c.label.replace(/\s/g,"")===String(x.category||"").replace(/\s/g,"")||c.id===x.categoryId)?.id||x.categoryId})).filter(x=>CATEGORIES.some(c=>c.id===x.categoryId))}
async function loadSermons({initial=false}={}){try{const response=await fetch(`./data/sermons.json?updated=${Date.now()}`,{cache:"no-store",headers:{"Cache-Control":"no-cache"}});if(!response.ok)throw new Error("archive");const next=normalizeSermons(await response.json()),selectedId=state.selected?.id||history.state?.sermonId||sermonIdFromHash(),changed=JSON.stringify(next)!==JSON.stringify(state.sermons);state.sermons=next;if(initial||changed)render();if(selectedId&&(initial||changed))openModal(selectedId,{pushHistory:false})}catch{if(initial)$("cards").innerHTML='<div class="empty"><strong>말씀을 불러오지 못했습니다</strong>잠시 후 다시 시도해 주세요.</div>'}}
loadSermons({initial:true});
document.addEventListener("visibilitychange",()=>{if(!document.hidden)loadSermons()});
window.addEventListener("focus",()=>loadSermons());
window.addEventListener("pageshow",()=>loadSermons());
