const CATEGORIES=["주일 1부","주일 2부","주일 3부","수요예배","핵심 메시지"];
const state={items:[],category:CATEGORIES[0],month:"",query:"",active:null};
const $=id=>document.getElementById(id); const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const norm=s=>String(s??"").toLowerCase().replace(/\s+/g,"").replace(/[.\-\/년월일]/g,"");
function highlight(text,q){const safe=esc(text);if(!q)return safe;const words=q.trim().split(/\s+/).filter(Boolean).sort((a,b)=>b.length-a.length);if(!words.length)return safe;return words.reduce((v,w)=>v.replace(new RegExp(esc(w).replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"gi"),m=>`<mark>${m}</mark>`),safe)}
function months(){return [...new Set(state.items.map(x=>x.date.slice(0,7)))].sort()}
function renderCategories(){$("categories").innerHTML=CATEGORIES.map(c=>`<button class="${c===state.category?'active':''}" data-cat="${c}">${c}</button>`).join("");document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;const ms=monthsForCategory();state.month=ms.at(-1)||months().at(-1)||"";render()})}
function monthsForCategory(){return [...new Set(state.items.filter(x=>x.category===state.category).map(x=>x.date.slice(0,7)))].sort()}
function render(){renderCategories();const q=state.query.trim(),nq=norm(q);let list=state.items.filter(x=>x.category===state.category);if(q)list=list.filter(x=>norm([x.title,x.passage,x.date,x.content].join(" ")).includes(nq));else list=list.filter(x=>x.date.startsWith(state.month));list.sort((a,b)=>b.date.localeCompare(a.date));const ms=monthsForCategory(),i=ms.indexOf(state.month);$("month").textContent=q?"검색 결과":state.month?`${Number(state.month.slice(5))}월`:"말씀";$("older").disabled=!!q||i<=0;$("newer").disabled=!!q||i<0||i>=ms.length-1;$("status").textContent=list.length?`${list.length}편의 말씀`:q?"검색 결과가 없습니다.":"이 달에 등록된 말씀이 없습니다.";$("cards").innerHTML=list.map(x=>`<article class="card"><div class="category">${esc(x.category)}</div><h2><button data-id="${esc(x.id)}">${highlight(x.title,q)}</button></h2><div class="passage">${highlight(x.passage||"성경 본문 미입력",q)}</div><time datetime="${esc(x.date)}">${highlight(formatDate(x.date),q)}</time></article>`).join("");document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>openReader(b.dataset.id))}
function formatDate(d){const [y,m,day]=d.split("-").map(Number);return `${y}. ${m}. ${day}.`}
function openReader(id){const x=state.items.find(v=>String(v.id)===String(id));if(!x)return;state.active=x;$("reader-meta").textContent=`${x.category} · ${formatDate(x.date)}`;$("reader-heading").textContent=x.title;$("reader-passage").textContent=x.passage||"";$("print").href=`./print.html?id=${encodeURIComponent(x.id)}`;const saved=localStorage.getItem(`sermon-effects:${x.id}`);if(saved){$("transcript").innerHTML=saved}else{$("transcript").replaceChildren(...x.content.split(/\n{2,}/).map(t=>{const p=document.createElement("p");p.textContent=t;return p}))}$("reader").showModal()}
function save(){if(state.active)localStorage.setItem(`sermon-effects:${state.active.id}`,$("transcript").innerHTML)}
$("search").oninput=e=>{state.query=e.target.value;render()};$("older").onclick=()=>{const a=monthsForCategory(),i=a.indexOf(state.month);if(i>0){state.month=a[i-1];render()}};$("newer").onclick=()=>{const a=monthsForCategory(),i=a.indexOf(state.month);if(i<a.length-1){state.month=a[i+1];render()}};$("close").onclick=$("reader-back").onclick=()=>$("reader").close();$("transcript").oninput=save;document.querySelectorAll("[data-command]").forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.command,false,b.dataset.value||null);save()});$("remove-format").onclick=()=>{document.execCommand("removeFormat");save()};$("clear-effects").onclick=()=>{if(!state.active)return;localStorage.removeItem(`sermon-effects:${state.active.id}`);$("transcript").replaceChildren(...state.active.content.split(/\n{2,}/).map(t=>{const p=document.createElement("p");p.textContent=t;return p}))};
fetch("./data/sermons.json").then(r=>r.json()).then(data=>{state.items=data;state.month=months().at(-1)||"";render()}).catch(()=>{$("status").textContent="말씀을 불러오지 못했습니다."});
