const CATEGORIES=[{id:"sunday1",label:"주일 1부"},{id:"sunday2",label:"주일 2부"},{id:"sunday3",label:"주일 3부"},{id:"wednesday",label:"수요예배"},{id:"core",label:"핵심 메시지"}];
const state={sermons:[],active:"sunday1",query:"",page:0,direction:"next",selected:null};
const $=id=>document.getElementById(id); const escapeHtml=s=>String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
function tokens(q){return q.trim().toLowerCase().split(/\s+/).filter(Boolean)}
function aliases(d){const[y,m,day]=d.split("-").map(Number),mm=String(m).padStart(2,"0"),dd=String(day).padStart(2,"0");return[d,`${y}-${m}-${day}`,`${y}.${m}.${day}`,`${y}. ${m}. ${day}.`,`${y}/${m}/${day}`,`${y}년 ${m}월 ${day}일`,`${y}${mm}${dd}`,`${m}/${day}`,`${mm}/${dd}`,`${m}-${day}`,`${m}.${day}`,`${m}월 ${day}일`,`${m}월${day}일`].join(" ").toLowerCase()}
function matches(x,q){return tokens(q).every(t=>[x.title,x.passage,x.content,aliases(x.date)].join(" ").toLowerCase().includes(t))}
function highlight(text,q,force=false){let html=escapeHtml(text);const ts=[...new Set(tokens(q).filter(t=>String(text).toLowerCase().includes(t)))].sort((a,b)=>b.length-a.length);if(!ts.length)return force&&q.trim()?`<mark class="search-highlight">${html}</mark>`:html;const re=new RegExp(`(${ts.map(t=>t.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")).join("|")})`,`gi`);return html.replace(re,'<mark class="search-highlight">$1</mark>')}
function formatDate(d){const[y,m,day]=d.split("-").map(Number);return`${y}. ${m}. ${day}.`}
function pages(){const list=state.sermons.filter(x=>x.categoryId===state.active&&matches(x,state.query));const grouped={};list.forEach(x=>(grouped[x.date.slice(0,7)]??=[]).push(x));return Object.entries(grouped).sort(([a],[b])=>b.localeCompare(a)).map(([month,sermons])=>({month,sermons:sermons.sort((a,b)=>b.date.localeCompare(a.date))}))}
function renderTabs(){$("tabs").innerHTML=CATEGORIES.map(c=>`<button role="tab" aria-selected="${state.active===c.id}" class="tab ${state.active===c.id?'active':''}" data-tab="${c.id}">${c.label}</button>`).join("");document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{state.active=b.dataset.tab;state.page=0;state.direction="next";render()})}
function render(){renderTabs();const ps=pages(),current=ps[Math.min(state.page,Math.max(ps.length-1,0))];if(current){const[y,m]=current.month.split("-");$("month-pagination").classList.remove("is-hidden");$("month-pagination").innerHTML=`<div class="month-heading"><span>Monthly archive</span><strong>${y}년 ${Number(m)}월</strong><small>${state.page+1} / ${ps.length} 페이지</small></div><div class="month-buttons"><button id="older" ${state.page>=ps.length-1?'disabled':''}>← 이전 페이지</button><button id="newer" ${state.page===0?'disabled':''}>다음 페이지 →</button></div>`;$("older").onclick=()=>{state.page++;state.direction="previous";render()};$("newer").onclick=()=>{state.page--;state.direction="next";render()}}else{$("month-pagination").classList.add("is-hidden")}
  const cards=$("cards");cards.className=`cards month-page month-page-${state.direction}`;cards.innerHTML=current?current.sermons.map(x=>`<article class="card card-${x.categoryId}"><div class="card-meta"><span class="badge">${x.category}</span><time class="card-date" datetime="${x.date}">${highlight(formatDate(x.date),state.query,tokens(state.query).every(t=>aliases(x.date).includes(t)))}</time></div><button class="card-title" data-open="${x.id}">${highlight(x.title,state.query)}</button>${x.passage?`<p class="passage">${highlight(x.passage,state.query)}</p>`:""}<p class="card-excerpt">${highlight(x.content.replace(/\s+/g," ").slice(0,135),state.query)}${x.content.length>135?'…':''}</p><div class="card-bottom"><button class="card-read" data-open="${x.id}">말씀 전체 읽기 <span class="read-arrow">→</span></button></div></article>`).join(""):`<div class="empty"><strong>첫 말씀을 기다리고 있습니다</strong>${state.query?'검색 조건에 맞는 녹취록이 없습니다.':`${CATEGORIES.find(c=>c.id===state.active).label} 녹취록이 등록되면 이곳에 최신순으로 나타납니다.`}</div>`;document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openModal(b.dataset.open))}
function clean(html){const doc=new DOMParser().parseFromString(html,"text/html"),allowed=new Set(["P","BR","B","STRONG","U","SPAN"]);[...doc.body.querySelectorAll("*")].reverse().forEach(el=>{if(!allowed.has(el.tagName)){el.replaceWith(...el.childNodes);return}const bg=el.tagName==="SPAN"?el.style.backgroundColor:"";[...el.attributes].forEach(a=>el.removeAttribute(a.name));if(el.tagName==="SPAN"&&bg)el.style.backgroundColor="rgb(255, 241, 138)"});return doc.body.innerHTML}
function baseHtml(content){return content.split(/\n{2,}/).filter(Boolean).map(p=>`<p>${escapeHtml(p)}</p>`).join("")}
function openModal(id){const x=state.sermons.find(s=>String(s.id)===String(id));if(!x)return;state.selected=x;$("modal-meta").innerHTML=`${x.category} · ${highlight(formatDate(x.date),state.query)}`;$("sermon-title").innerHTML=highlight(x.title,state.query);$("modal-passage").innerHTML=highlight(x.passage||"",state.query);$("modal-passage").hidden=!x.passage;$("print-link").href=`./print.html?id=${encodeURIComponent(x.id)}`;$("transcript").innerHTML=clean(localStorage.getItem(`sermon-annotation-${x.id}`)||baseHtml(x.content));$("modal-backdrop").classList.remove("is-hidden");document.body.style.overflow="hidden"}
function closeModal(){$("modal-backdrop").classList.add("is-hidden");document.body.style.overflow="";state.selected=null}
function save(){if(state.selected)localStorage.setItem(`sermon-annotation-${state.selected.id}`,clean($("transcript").innerHTML))}
$("search").oninput=e=>{state.query=e.target.value;state.page=0;render()};$("close-modal").onclick=closeModal;$("modal-backdrop").onmousedown=e=>{if(e.target===$("modal-backdrop"))closeModal()};document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});document.querySelectorAll("[data-command]").forEach(b=>b.onmousedown=e=>{e.preventDefault();const sel=getSelection();if(!sel||sel.isCollapsed||!$("transcript").contains(sel.anchorNode)||!$("transcript").contains(sel.focusNode)){$("annotation-guide").firstChild.textContent="먼저 녹취록 안에서 효과를 적용할 문장을 선택해 주세요.";return}document.execCommand(b.dataset.command,false,b.dataset.command==="hiliteColor"?"#fff18a":undefined);save()});$("clear-effects").onmousedown=e=>{e.preventDefault();if(state.selected&&confirm("이 말씀에 표시한 모든 효과를 지울까요?")){localStorage.removeItem(`sermon-annotation-${state.selected.id}`);$("transcript").innerHTML=baseHtml(state.selected.content)}};$("transcript").oninput=save;
fetch("./data/sermons.json").then(r=>r.json()).then(data=>{state.sermons=data.map(x=>({...x,categoryId:CATEGORIES.find(c=>c.label===x.category)?.id||x.categoryId}));render()}).catch(()=>{$("cards").innerHTML='<div class="empty"><strong>말씀을 불러오지 못했습니다</strong>잠시 후 다시 시도해 주세요.</div>'});
